; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
; Modules
projects[ctools][download][branch] = "1.6-rc1"
projects[ctools][download][revision] = "2678da8"
projects[ctools][download][type] = "git"
projects[ctools][subdir] = "contrib"

projects[manualcrop][download][branch] = "1.x-dev"
projects[manualcrop][download][revision] = "332ffcc"
projects[manualcrop][download][type] = "git"
projects[manualcrop][subdir] = "contrib"

projects[panelizer][download][branch] = "3.x-dev"
projects[panelizer][download][revision] = "dd5aacc"
projects[panelizer][download][type] = "git"
projects[panelizer][subdir] = "contrib"

projects[panels][download][branch] = "3.x-dev"
projects[panels][download][revision] = "f7ed1af"
projects[panels][download][type] = "git"
projects[panels][subdir] = "contrib"

projects[superfish][download][branch] = "1.x-dev"
projects[superfish][download][revision] = "fa3d7c6"
projects[superfish][download][type] = "git"
projects[superfish][subdir] = "contrib"

projects[uuid][download][branch] = "1.x-dev"
projects[uuid][download][revision] = "a7bf2db"
projects[uuid][download][type] = "git"
projects[uuid][subdir] = "contrib"

projects[uuid_features][download][branch] = "1.x-dev"
projects[uuid_features][download][revision] = "166fb9f"
projects[uuid_features][download][type] = "git"
projects[uuid_features][subdir] = "contrib"

projects[admin_menu][patch][0] = "https://www.drupal.org/files/admin_menu-search-disappeared-1916812-13.patch"
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[image_combination_effects][patch][0] = "https://www.drupal.org/files/issues/ICE-fix-fatal-typecast-error-228133-2.patch"
projects[image_combination_effects][subdir] = "contrib"
projects[image_combination_effects][version] = "1.0-alpha1"

projects[features][download][branch] = "7.x-2.x"
projects[features][download][type] = "git"
projects[features][patch] = "https://www.drupal.org/files/issues/1064340-features-files-13.patch"
projects[features][subdir] = "contrib"

projects[addressfield][patch][0] = "https://www.drupal.org/files/issues/addressfield-nonempty-1263316-98.patch"
projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0"

projects[field_collection][patch][0] = "https://www.drupal.org/files/issues/field_collection-host_entity_tokens-1372652-74.patch"
projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta8"

projects[addressfield_staticmap][subdir] = "contrib"
projects[addressfield_staticmap][version] = "1.0"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.3"

projects[adminimal_admin_menu][subdir] = "contrib"
projects[adminimal_admin_menu][version] = "1.5"

projects[auto_entitylabel][subdir] = "contrib"
projects[auto_entitylabel][version] = "1.3"

projects[better_exposed_filters][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.0"

projects[bg_image][subdir] = "contrib"
projects[bg_image][version] = "1.4"

projects[bg_image_formatter][subdir] = "contrib"
projects[bg_image_formatter][version] = "1.3"

projects[computed_field][subdir] = "contrib"
projects[computed_field][version] = "1.0"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.16"

projects[coffee][subdir] = "contrib"
projects[coffee][version] = "2.2"

projects[colorbox][subdir] = "contrib"
projects[colorbox][version] = "2.8"

projects[content_menu][subdir] = "contrib"
projects[content_menu][version] = "1.0"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[email_registration][subdir] = "contrib"
projects[email_registration][version] = "1.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entity_view_mode][subdir] = "contrib"
projects[entity_view_mode][version] = "1.0-rc1"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[features_override][subdir] = "contrib"
projects[features_override][version] = "2.0-rc2"

projects[fences][subdir] = "contrib"
projects[fences][version] = "1.0"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.4"

projects[filefield_paths][subdir] = "contrib"
projects[filefield_paths][version] = "1.0-beta4"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.5"

projects[geocoder][subdir] = "contrib"
projects[geocoder][version] = "1.2"

projects[geofield][subdir] = "contrib"
projects[geofield][version] = "2.3"

projects[geophp][subdir] = "contrib"
projects[geophp][version] = "1.7"

projects[imagecache_actions][subdir] = "contrib"
projects[imagecache_actions][version] = "1.5"

projects[imagecache_token][subdir] = "contrib"
projects[imagecache_token][version] = "1.x-dev"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.9"

projects[imce_filefield][subdir] = "contrib"
projects[imce_filefield][version] = "1.0"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.5"

projects[inline_messages][subdir] = "contrib"
projects[inline_messages][version] = "1.0"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.5"

projects[leaflet][subdir] = "contrib"
projects[leaflet][version] = "1.1"

projects[leaflet_more_maps][subdir] = "contrib"
projects[leaflet_more_maps][version] = "1.10"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.3"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "3.3"

projects[masquerade][subdir] = "contrib"
projects[masquerade][version] = "1.0-rc7"

projects[menu_attributes][subdir] = "contrib"
projects[menu_attributes][version] = "1.0-rc3"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[panels_everywhere][subdir] = "contrib"
projects[panels_everywhere][version] = "1.0-rc2"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[phone][subdir] = "contrib"
projects[phone][version] = "1.0-beta1"

projects[quicktabs][subdir] = "contrib"
projects[quicktabs][version] = "3.6"

projects[range][subdir] = "contrib"
projects[range][version] = "1.2"

projects[services][subdir] = "contrib"
projects[services][version] = "3.11"

projects[simplify][subdir] = "contrib"
projects[simplify][version] = "3.2"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[themekey][subdir] = "contrib"
projects[themekey][version] = "3.3"

projects[title][subdir] = "contrib"
projects[title][version] = "1.0-alpha7"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[views_bootstrap][subdir] = "contrib"
projects[views_bootstrap][version] = "3.1"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[webform][subdir] = "contrib"
projects[webform][version] = "4.2"

projects[webform_phone][subdir] = "contrib"
projects[webform_phone][version] = "1.21"

projects[webform_uuid][subdir] = "contrib"
projects[webform_uuid][version] = "1.1"

projects[youtube][subdir] = "contrib"
projects[youtube][version] = "1.3"

; Themes
projects[adminimal_theme][subdir] = "contrib"
projects[adminimal_theme][version] = "1.20"
projects[adminimal_theme][type] = "theme"

projects[bootstrap][subdir] = "contrib"
projects[bootstrap][version] = "3.0"
projects[bootstrap][type] = "theme"

projects[omega][subdir] = "contrib"
projects[omega][version] = "4.3"
projects[omega][type] = "theme"

; Libraries
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor%20for%20Drupal/edit/ckeditor_4.4.3_edit.zip"
libraries[ckeditor][type] = "library"

libraries[leaflet][download][type] = "get"
libraries[leaflet][download][url] = "http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.7.3.zip"
libraries[leaflet][type] = "library"

libraries[superfish][download][type] = "get"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal/archive/master.zip"
libraries[superfish][type] = "library"

