; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
; Themes
projects[adminimal_theme][subdir] = "contrib"
projects[adminimal_theme][version] = "1.21"
projects[adminimal_theme][type] = "theme"

projects[bootstrap][subdir] = "contrib"
projects[bootstrap][version] = "3.0"
projects[bootstrap][type] = "theme"

projects[omega][subdir] = "contrib"
projects[omega][version] = "4.3"
projects[omega][type] = "theme"

; Modules
projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.1"
projects[addressfield][patch][0] = "https://www.drupal.org/files/issues/addressfield-nonempty-1263316-98.patch"

projects[addressfield_tokens][subdir] = "contrib"
projects[addressfield_tokens][version] = "1.5"


projects[addressfield_staticmap][subdir] = "contrib"
projects[addressfield_staticmap][version] = "1.0"

projects[addthis][subdir] = "contrib"
projects[addthis][version] = "4.0-alpha6"

projects[addtoany][subdir] = "contrib"
projects[addtoany][version] = "4.10"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"
projects[admin_menu][patch][0] = "https://www.drupal.org/files/admin_menu-search-disappeared-1916812-13.patch"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.5"

projects[adminimal_admin_menu][subdir] = "contrib"
projects[adminimal_admin_menu][version] = "1.5"

projects[advagg][subdir] = "contrib"
projects[advagg][version] = "2.10"

projects[apdqc][subdir] = "contrib"
projects[apdqc][version] = "1.0-beta4"

projects[auto_entitylabel][subdir] = "contrib"
projects[auto_entitylabel][version] = "1.3"

projects[better_exposed_filters][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.2"

projects[better_formats][subdir] = "contrib"
projects[better_formats][version] = "1.0-beta1"

projects[bg_image][subdir] = "contrib"
projects[bg_image][version] = "1.4"

projects[bg_image_formatter][subdir] = "contrib"
projects[bg_image_formatter][version] = "1.3"

projects[breakpoints][subdir] = "contrib"
projects[breakpoints][version] = "1.4"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.3"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.16"
projects[ckeditor][patch][0] = "https://www.drupal.org/files/issues/Issue_2454933.patch"

projects[cloudflare][subdir] = "contrib"
projects[cloudflare][version] = "1.0-beta4"

projects[coffee][subdir] = "contrib"
projects[coffee][version] = "2.2"

projects[colorbox][subdir] = "contrib"
projects[colorbox][version] = "2.10"

projects[computed_field][subdir] = "contrib"
projects[computed_field][version] = "1.0"

projects[conditional_fields][subdir] = "contrib"
projects[conditional_fields][version] = "3.0-alpha2"
projects[conditional_fields][patch][0] = "https://www.drupal.org/files/issues/filled_with_a_value-2142691-16.patch"

projects[content_menu][subdir] = "contrib"
projects[content_menu][version] = "1.0"

projects[contextual_range_filter][subdir] = "contrib"
projects[contextual_range_filter][version] = "1.7"

projects[countries][subdir] = "contrib"
projects[countries][version] = "2.3"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[disqus][subdir] = "contrib"
projects[disqus][version] = "1.12"

projects[email][subdir] = "contrib"
projects[email][version] = "1.3"

projects[email_registration][subdir] = "contrib"
projects[email_registration][version] = "1.2"

projects[editablefields][subdir] = "contrib"
projects[editablefields][version] = "1.0-alpha2"

projects[elysia_cron][subdir] = "contrib"
projects[elysia_cron][version] = "2.1"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[entity_view_mode][subdir] = "contrib"
projects[entity_view_mode][version] = "1.0-rc1"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[environment][subdir] = "contrib"
projects[environment][version] = "1.0"

projects[environment_indicator][subdir] = "contrib"
projects[environment_indicator][version] = "2.6"

projects[eva][subdir] = "contrib"
projects[eva][version] = "1.2"

projects[expire][subdir] = "contrib"
projects[expire][version] = "2.0-rc4"

projects[fb_likebox][subdir] = "contrib"
projects[fb_likebox][version] = "2.2"

projects[features][subdir] = "contrib"
projects[features][version] = "2.10"

projects[features_override][subdir] = "contrib"
projects[features_override][version] = "2.0-rc2"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-beta1"

projects[feeds_tamper][subdir] = "contrib"
projects[feeds_tamper][version] = "1.1"

projects[feeds_xpathparser][subdir] = "contrib"
projects[feeds_xpathparser][version] = "1.0"

projects[fences][subdir] = "contrib"
projects[fences][version] = "1.0"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta8"
projects[field_collection][patch][0] = "https://www.drupal.org/files/issues/field_collection-host_entity_tokens-1372652-74.patch"

projects[field_collection_feeds][subdir] = "contrib"
projects[field_collection_feeds][version] = "1.0-alpha3"
projects[field_collection_feeds][patch][0] = "https://www.drupal.org/files/issues/FeedsUpdateIssue-1921128-12.patch"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.5"

projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.0-beta2"

projects[field_validation][subdir] = "contrib"
projects[field_validation][download][branch] = "2.x-dev"
projects[field_validation][download][revision] = "63e1e83"
projects[field_validation][download][type] = "git"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-beta1"

projects[filefield_paths][subdir] = "contrib"
projects[filefield_paths][download][branch] = "1.x-dev"
projects[filefield_paths][download][revision] = "e016a2e"
projects[filefield_paths][download][type] = "git"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.9"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.6"
projects[flag][patch][0] = "https://www.drupal.org/files/issues/flag-broken-1925922-131.patch"
projects[flag][patch][1] = "https://www.drupal.org/files/issues/1925922-flag-fixed-warning-76.patch"
projects[flag][patch][2] = "https://www.drupal.org/files/issues/line-130-fixer-upper-rater-19252922-46_1.patch"

projects[flexslider][subdir] = "contrib"
projects[flexslider][version] = "2.0-alpha3"

projects[flippy][subdir] = "contrib"
projects[flippy][version] = "1.4"

projects[geocoder][subdir] = "contrib"
projects[geocoder][version] = "1.2"

projects[geofield][subdir] = "contrib"
projects[geofield][version] = "2.3"
projects[geofield][patch][0] = "https://www.drupal.org/files/issues/geofield-feeds_import_not_saving-2534822-46.patch"

projects[geophp][subdir] = "contrib"
projects[geophp][version] = "1.7"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "2.1"

projects[googtube][subdir] = "contrib"
projects[googtube][version] = "2.1"
projects[googtube][patch][0] = "https://www.drupal.org/files/issues/googtube-2428511-match-https-urls-too.patch"
projects[googtube][patch][1] = "https://www.drupal.org/files/issues/googtube-fix-https-embed-1822354-9.patch"

projects[gtranslate][subdir] = "contrib"
projects[gtranslate][version] = "1.10"

projects[hidden_captcha][subdir] = "contrib"
projects[hidden_captcha][version] = "1.0"

projects[hybridauth][subdir] = "contrib"
projects[hybridauth][version] = "2.15"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.13"

projects[iframe][subdir] = "contrib"
projects[iframe][version] = "1.3"

projects[imageapi_optimize][subdir] = "contrib"
projects[imageapi_optimize][version] = "1.2"
projects[imageapi_optimize][patch][0] = "https://www.drupal.org/files/issues/imageapi_optimize-clean_up_temp_files-2495943-1.patch"

projects[imagecache_actions][subdir] = "contrib"
projects[imagecache_actions][version] = "1.5"

projects[imagecache_token][subdir] = "contrib"
projects[imagecache_token][version] = "1.x-dev"

projects[imagefield_tokens][subdir] = "contrib"
projects[imagefield_tokens][download][branch] = "1.x-dev"
projects[imagefield_tokens][download][revision] = "9244539"
projects[imagefield_tokens][download][type] = "git"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.9"

projects[imce_filefield][subdir] = "contrib"
projects[imce_filefield][version] = "1.1"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.6"

projects[inline_messages][subdir] = "contrib"
projects[inline_messages][version] = "1.0"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "3.0-alpha2"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[label_help][subdir] = "contrib"
projects[label_help][version] = "1.2"

projects[lang_dropdown][subdir] = "contrib"
projects[lang_dropdown][version] = "2.5"

projects[leaflet][subdir] = "contrib"
projects[leaflet][version] = "1.1"
projects[leaflet][patch][0] = "https://www.drupal.org/files/issues/field-formatter-errors-2185767-6.patch"
projects[leaflet][patch][1] = "https://www.drupal.org/files/issues/taxonomy-terms-attached-image-fields-as-markers-2178231-25_0.patch"

projects[leaflet_more_maps][subdir] = "contrib"
projects[leaflet_more_maps][version] = "1.11"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.3"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "3.3"

projects[logentries][subdir] = "contrib"
projects[logentries][version] = "1.3"

projects[mailchimp][subdir] = "contrib"
projects[mailchimp][version] = "3.6"

projects[mailsystem][subdir] = "contrib"
projects[mailsystem][download][branch] = "3.x-dev"
projects[mailsystem][download][revision] = "4c957ae"
projects[mailsystem][download][type] = "git"

projects[manualcrop][subdir] = "contrib"
projects[manualcrop][version] = "1.5"
projects[manualcrop][patch][0] = "https://www.drupal.org/files/issues/manualcrop--automatic_default_crop--1.5.diff"

projects[masquerade][subdir] = "contrib"
projects[masquerade][version] = "1.0-rc7"

projects[media][subdir] = "contrib"
projects[media][version] = "2.x-dev"

projects[media_ckeditor][subdir] = "contrib"
projects[media_ckeditor][version] = "2.0-alpha1"

projects[media_oembed][subdir] = "contrib"
projects[media_oembed][version] = "2.5"

projects[media_youtube][subdir] = "contrib"
projects[media_youtube][version] = "3.0"

projects[menu_attributes][subdir] = "contrib"
projects[menu_attributes][version] = "1.0-rc3"

projects[menu_token][subdir] = "contrib"
projects[menu_token][version] = "1.0-beta6"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.5"

projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.8"

projects[mimemail][subdir] = "contrib"
projects[mimemail][version] = "1.0-beta3"

projects[mixpanel][subdir] = "contrib"
projects[mixpanel][download][branch] = "1.x-dev"
projects[mixpanel][download][revision] = "14f8ee8"
projects[mixpanel][download][type] = "git"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0"

projects[modernizr][subdir] = "contrib"
projects[modernizr][version] = "3.7"

projects[multiupload_filefield_widget][subdir] = "contrib"
projects[multiupload_filefield_widget][version] = "1.13"

projects[multiupload_imagefield_widget][subdir] = "contrib"
projects[multiupload_imagefield_widget][version] = "1.3"

projects[multiple_selects][subdir] = "contrib"
projects[multiple_selects][version] = "1.2"

projects[oauth][subdir] = "contrib"
projects[oauth][version] = "3.2"

projects[office_hours][subdir] = "contrib"
projects[office_hours][version] = "1.4"

projects[openid_selector][subdir] = "contrib"
projects[openid_selector][version] = "1.x-dev"

projects[openid_sso_relying][subdir] = "contrib"
projects[openid_sso_relying][version] = "1.0-beta3"

projects[owlcarousel][subdir] = "contrib"
projects[owlcarousel][version] = "1.5"

projects[pagepreview][subdir] = "contrib"
projects[pagepreview][version] = "1.0-alpha1"

projects[panelizer][subdir] = "contrib"
projects[panelizer][download][branch] = "3.x-dev"
projects[panelizer][download][revision] = "dd5aacc"
projects[panelizer][download][type] = "git"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.5"

projects[panels_content_cache][subdir] = "contrib"
projects[panels_content_cache][version] = "1.2"

projects[panels_everywhere][subdir] = "contrib"
projects[panels_everywhere][version] = "1.0-rc2"

projects[paragraphs][subdir] = "contrib"
projects[paragraphs][version] = "1.0-beta6"

projects[path_redirect_import][subdir] = "contrib"
projects[path_redirect_import][version] = "1.0-rc4"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.3"

projects[patterns][subdir] = "contrib"
projects[patterns][version] = "2.2"

projects[phone][subdir] = "contrib"
projects[phone][version] = "1.0-beta1"

projects[photoswipe][subdir] = "contrib"
projects[photoswipe][version] = "2.0-beta2"

projects[picture][subdir] = "contrib"
projects[picture][version] = "2.13"

projects[profile2][subdir] = "contrib"
projects[profile2][version] = "1.3"

projects[quicktabs][subdir] = "contrib"
projects[quicktabs][download][branch] = "3.x-dev"
projects[quicktabs][download][revision] = "aeeaaa9"
projects[quicktabs][download][type] = "git"

projects[rabbit_hole][subdir] = "contrib"
projects[rabbit_hole][version] = "2.23"

projects[range][subdir] = "contrib"
projects[range][version] = "1.3"

projects[redirect][subdir] = "contrib"
projects[redirect][download][branch] = "2.x-dev"
projects[redirect][download][revision] = "cfe2e89"
projects[redirect][download][type] = "git"

projects[required_by_role][subdir] = "contrib"
projects[required_by_role][version] = "1.7"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.7"

projects[save_edit][subdir] = "contrib"
projects[save_edit][version] = "1.0-beta1"

projects[search404][subdir] = "contrib"
projects[search404][version] = "1.3"

projects[search_by_page][subdir] = "contrib"
projects[search_by_page][version] = "1.4"

projects[segmentio][subdir] = "contrib"
projects[segmentio][version] = "1.1"

projects[services][subdir] = "contrib"
projects[services][version] = "3.12"

projects[sharethis][subdir] = "contrib"
projects[sharethis][download][branch] = "2.x-dev"
projects[sharethis][download][revision] = "b51ebc0"
projects[sharethis][download][type] = "git"
projects[sharethis][patch][0] = "https://www.drupal.org/files/issues/1425744-sharethis-popup-9.patch"

projects[simplify][subdir] = "contrib"
projects[simplify][version] = "3.3"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.3"

projects[s3fs][subdir] = "contrib"
projects[s3fs][version] = "2.1"
projects[s3fs][patch][0] = "https://www.drupal.org/files/issues/s3fs-allow_uri_scheme_overrides-2495559-1.patch"

projects[save_draft][subdir] = "contrib"
projects[save_draft][version] = "1.4"

projects[scheduler][subdir] = "contrib"
projects[scheduler][version] = "1.3"

projects[service_links][subdir] = "contrib"
projects[service_links][version] = "2.3"

projects[shareaholic][subdir] = "contrib"
projects[shareaholic][version] = "3.26"

projects[smtp][subdir] = "contrib"
projects[smtp][version] = "1.2"

projects[socialmedia][subdir] = "contrib"
projects[socialmedia][version] = "1.0-beta15"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][version] = "2.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[subpathauto][subdir] = "contrib"
projects[subpathauto][version] = "1.3"

projects[subscriptions][subdir] = "contrib"
projects[subscriptions][version] = "1.1"

projects[superfish][subdir] = "contrib"
projects[superfish][download][branch] = "1.x-dev"
projects[superfish][download][revision] = "fa3d7c6"
projects[superfish][download][type] = "git"

projects[themekey][subdir] = "contrib"
projects[themekey][version] = "3.3"

projects[title][subdir] = "contrib"
projects[title][version] = "1.0-alpha8"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[token_filter][subdir] = "contrib"
projects[token_filter][version] = "1.1"

projects[twitter][subdir] = "contrib"
projects[twitter][version] = "5.11"

projects[uuid][subdir] = "contrib"
projects[uuid][download][branch] = "1.x-dev"
projects[uuid][download][revision] = "a7bf2db"
projects[uuid][download][type] = "git"
projects[uuid][patch][0] = "https://www.drupal.org/files/issues/uuid_add-paragraphs-module-support-2471174.patch"

projects[uuid_features][subdir] = "contrib"
projects[uuid_features][download][branch] = "1.x-dev"
projects[uuid_features][download][revision] = "84db2dd"
projects[uuid_features][download][type] = "git"
projects[uuid_features][patch][0] = "https://www.drupal.org/files/issues/uuid_features-export%E2%80%93files-in%E2%80%93file-fields-with-taxonomy-terms-2454405-1.patch"

projects[user_role_field][subdir] = "contrib"
projects[user_role_field][version] = "1.1"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[varnish][subdir] = "contrib"
projects[varnish][version] = "1.0-beta3"

projects[views][subdir] = "contrib"
projects[views][version] = "3.14"
projects[views][patch][0] = "https://www.drupal.org/files/views-area-results-plural-1793500-1.patch"
projects[views][patch][1] = "https://www.drupal.org/files/issues/views-taxonomy_multiple_term_names-1248300-46.patch"

projects[views_accordion][subdir] = "contrib"
projects[views_accordion][version] = "1.1"

projects[views_bootstrap][subdir] = "contrib"
projects[views_bootstrap][version] = "3.1"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.3"

projects[views_content_cache][subdir] = "contrib"
projects[views_content_cache][version] = "3.0-alpha3"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta8"

projects[views_datasource][subdir] = "contrib"
projects[views_datasource][version] = "1.0-alpha2"

projects[views_field_view][subdir] = "contrib"
projects[views_field_view][version] = "1.1"

projects[views_megarow][subdir] = "contrib"
projects[views_megarow][version] = "1.6"

projects[views_load_more][subdir] = "contrib"
projects[views_load_more][version] = "1.5"

projects[views_rss][subdir] = "contrib"
projects[views_rss][version] = "2.0-rc4"

projects[webform][subdir] = "contrib"
projects[webform][version] = "4.9"

projects[webform_phone][subdir] = "contrib"
projects[webform_phone][version] = "1.21"

projects[webform_uuid][subdir] = "contrib"
projects[webform_uuid][version] = "1.1"

projects[yoast_seo][subdir] = "contrib"
projects[yoast_seo][version] = "1.0-beta2"

projects[youtube][subdir] = "contrib"
projects[youtube][version] = "1.6"


; Libraries
libraries[awssdk2][download][type] = "get"
libraries[awssdk2][download][url] = "https://github.com/aws/aws-sdk-php/releases/download/2.7.25/aws.zip"
libraries[awssdk2][directory_name] = "awssdk2"
libraries[awssdk2][destination] = "libraries"
libraries[awssdk2][type] = "library"

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor%20for%20Drupal/edit/ckeditor_4.4.3_edit.zip"
libraries[ckeditor][type] = "library"

libraries[flexslider][download][type] = "get"
libraries[flexslider][download][url] = "https://github.com/woothemes/FlexSlider/archive/master.zip"
libraries[flexslider][type] = "library"

libraries[hybridauth][download][type] = "get"
libraries[hybridauth][download][url] = "https://github.com/hybridauth/hybridauth/archive/master.zip"
libraries[hybridauth][type] = "library"

libraries[jquery.imagesloaded][download][type] = "get"
libraries[jquery.imagesloaded][download][url] = "https://github.com/desandro/imagesloaded/archive/v2.1.2.tar.gz"
libraries[jquery.imagesloaded][type] = "library"

libraries[jquery.imgareaselect][download][type] = "get"
libraries[jquery.imgareaselect][download][url] = "http://odyniec.net/projects/imgareaselect/jquery.imgareaselect-0.9.10.zip"
libraries[jquery.imgareaselect][type] = "library"

libraries[leaflet][download][type] = "get"
libraries[leaflet][download][url] = "http://cdn.leafletjs.com/downloads/leaflet-0.7.3.zip"
libraries[leaflet][type] = "library"

libraries[logentries][download][type] = "get"
libraries[logentries][download][url] = "https://github.com/logentries/le_php/archive/v1.6.zip"
libraries[logentries][type] = "library"

libraries[mailchimp][download][type] = "get"
libraries[mailchimp][download][url] = "https://bitbucket.org/mailchimp/mailchimp-api-php/get/2.0.4.zip"
libraries[mailchimp][type] = "library"

libraries[openid_selector][download][type] = "get"
libraries[openid_selector][download][url] = "http://openid-selector.googlecode.com/files/openid-selector-1.3.zip"
libraries[openid_selector][directory_name] = "openid-selector"
libraries[openid_selector][destination] = "../../sites/all/libraries"
libraries[openid_selector][type] = "library"

libraries[owlcarousel][download][type] = "get"
libraries[owlcarousel][download][url] = "https://github.com/OwlFonk/OwlCarousel/archive/master.zip"
libraries[owlcarousel][directory_name] = "owl-carousel"
libraries[owlcarousel][destination] = "../../sites/all/libraries"
libraries[owlcarousel][type] = "library"

libraries[photoswipe][download][type] = "get"
libraries[photoswipe][download][url] = "https://github.com/dimsemenov/PhotoSwipe/archive/master.zip"
libraries[photoswipe][type] = "library"

libraries[superfish][download][type] = "get"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal/archive/master.zip"
libraries[superfish][type] = "library"

