; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][subdir] = "contrib"
projects[drupal][patch][0] = "https://www.drupal.org/files/issues/drupal-clean_up_temp_files-2496173-1-d7.patch"
projects[drupal][version] = "7.52"
projects[drupal][type] = "core"

; Profiles
projects[rune][type] = "profile"
projects[rune][download][url] = "https://github.com/poetic/rune.git"
projects[rune][download][type] = "git"
projects[rune][download][tag] = "0.2.1"

