api = 2
core = 7.x

;projects[] = addressfield                 // patched
projects[] = addressfield_staticmap
;projects[] = admin_menu                   // patched
projects[] = admin_views
projects[] = adminimal_admin_menu
projects[] = auto_entitylabel
projects[] = better_exposed_filters
projects[] = bg_image
projects[] = bg_image_formatter
projects[] = computed_field
projects[] = ckeditor
projects[] = coffee
projects[] = colorbox
projects[] = content_menu
;projects[] = ctools                       // pinned
projects[] = date
projects[] = diff
projects[] = email_registration
projects[] = entity
projects[] = entity_view_mode
projects[] = entityreference
;projects[] = features                     // patched
projects[] = features_override
projects[] = fences
projects[] = field_collection
projects[] = field_group
projects[] = filefield_paths
projects[] = flag
projects[] = geocoder
projects[] = geofield
projects[] = geophp
;projects[] = image_combination_effects    // patched
projects[] = imagecache_actions
projects[] = imagecache_token
projects[] = imce
projects[] = imce_filefield
projects[] = inline_entity_form
projects[] = inline_messages
projects[] = jquery_update
projects[] = leaflet
projects[] = leaflet_more_maps
projects[] = libraries
projects[] = link
projects[] = linkit
;projects[] = manualcrop                   // pinned
projects[] = masquerade
projects[] = menu_attributes
projects[] = module_filter
;projects[] = panelizer                    // pinned
;projects[] = panels                       // pinned
projects[] = panels_everywhere
projects[] = pathauto
projects[] = phone
projects[] = quicktabs
projects[] = range
projects[] = services
projects[] = simplify
projects[] = strongarm
;projects[] = superfish                    // pinned
projects[] = themekey
projects[] = title
projects[] = token
;projects[] = uuid                         // pinned
;projects[] = uuid_features                // patched
projects[] = views
projects[] = views_bootstrap
projects[] = views_bulk_operations
projects[] = webform
projects[] = webform_phone
projects[] = webform_uuid
projects[] = youtube


;; Include overrides
includes[] = modules/pins.make
includes[] = modules/patches.make
includes[] = modules/libraries.make
